import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js';

const scene=new THREE.Scene(); scene.background=new THREE.Color(0x8fb4c7); scene.fog=new THREE.Fog(0x8fb4c7,35,130);
const camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.05,250); const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; document.body.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xdff6ff,0x33402b,2)); const sun=new THREE.DirectionalLight(0xffffff,3); sun.position.set(-30,45,20); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048); scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshStandardMaterial({color:0x526b45,roughness:1})); ground.rotation.x=-Math.PI/2; ground.receiveShadow=true; scene.add(ground);
function box(x,y,z,w,h,d,c){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:c}));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;scene.add(m);return m}
for(let i=0;i<28;i++){const x=(Math.random()-.5)*100,z=(Math.random()-.5)*100;if(Math.hypot(x,z)<14)continue;box(x,1.5,z,3,3,3,0x777e83);}
for(let i=0;i<18;i++){const x=(Math.random()-.5)*100,z=(Math.random()-.5)*100;if(Math.hypot(x,z)<16)continue;const trunk=box(x,2,z,1.2,4,1.2,0x55351f);const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(3.2,1),new THREE.MeshStandardMaterial({color:0x234b2b}));crown.position.set(x,5,z);crown.castShadow=true;scene.add(crown)}
const player=new THREE.Group(); player.position.set(0,0,6); scene.add(player);
const body=new THREE.Mesh(new THREE.CapsuleGeometry(.55,1.15,6,12),new THREE.MeshStandardMaterial({color:0xdddff2})); body.position.y=1.1;body.castShadow=true;player.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.5,16,12),new THREE.MeshStandardMaterial({color:0xcad0e0}));head.position.y=2.1;head.castShadow=true;player.add(head);
const gun=new THREE.Group(); gun.position.set(.48,1.35,-.7); player.add(gun); const g1=new THREE.Mesh(new THREE.BoxGeometry(.18,.18,.9),new THREE.MeshStandardMaterial({color:0x22252a}));g1.position.z=-.4;gun.add(g1);const g2=new THREE.Mesh(new THREE.BoxGeometry(.28,.25,.35),new THREE.MeshStandardMaterial({color:0x454a50}));gun.add(g2);
const items=[]; const itemColors=[0x9b7449,0x777777,0xe9f2f4,0x536b8d]; function spawnItem(){const g=new THREE.Group();const c=itemColors[Math.floor(Math.random()*itemColors.length)];g.add(new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial({color:c})));g.position.set((Math.random()-.5)*35,.55,(Math.random()-.5)*55);g.userData.v=new THREE.Vector3();g.userData.held=false;scene.add(g);items.push(g)} for(let i=0;i<20;i++)spawnItem();
const bots=[];for(let i=0;i<8;i++){const b=new THREE.Group();const bc=new THREE.Mesh(new THREE.CapsuleGeometry(.5,1,6,10),new THREE.MeshStandardMaterial({color:0x7d3942}));bc.position.y=1;b.add(bc);const bh=new THREE.Mesh(new THREE.SphereGeometry(.45,12,8),new THREE.MeshStandardMaterial({color:0x9c6870}));bh.position.y=1.95;b.add(bh);b.position.set((Math.random()-.5)*50,0,(Math.random()-.5)*70);scene.add(b);bots.push({o:b,dir:new THREE.Vector3(Math.random()-.5,0,Math.random()-.5).normalize(),hp:100})}
let first=false,running=false,score=0,hp=100,yaw=0,pitch=0,keys={},held=null;const clock=new THREE.Clock();
function flash(t){const e=document.getElementById('msg');e.textContent=t;e.style.opacity=1;setTimeout(()=>e.style.opacity=0,700)}
function nearest(){let best=null,d=2.5;for(const it of items){if(it.userData.held)continue;const q=it.position.distanceTo(player.position);if(q<d){d=q;best=it}}return best}
function use(){if(held){held.userData.held=false;held.position.copy(player.position);held.position.y=.7;held=null;flash('ПОЛОЖЕНО');return}const it=nearest();if(!it)return flash('НЕТ ПРЕДМЕТА РЯДОМ');it.userData.held=true;held=it;flash('ВЗЯТО')}
function throwIt(){if(!held)return;held.userData.held=false;held.position.copy(player.position).add(new THREE.Vector3(Math.sin(yaw),.2,Math.cos(yaw)));held.userData.v.set(Math.sin(yaw)*14,5,Math.cos(yaw)*14);held=null;flash('БРОСОК')}
function shoot(){const ray=new THREE.Raycaster();const dir=new THREE.Vector3();camera.getWorldDirection(dir);ray.set(camera.position,dir);const hits=ray.intersectObjects(bots.flatMap(b=>b.o.children),true);if(hits.length){let o=hits[0].object;while(o.parent&&!bots.some(b=>b.o===o))o=o.parent;const b=bots.find(b=>b.o===o);if(b){b.hp-=25;score+=25;document.getElementById('score').textContent='СЧЁТ: '+score;if(b.hp<=0){b.o.position.set((Math.random()-.5)*55,0,(Math.random()-.5)*75);b.hp=100}}}}
function setCamera(dt){const target=new THREE.Vector3();if(first){camera.position.copy(player.position).add(new THREE.Vector3(0,1.65,0));camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch;gun.visible=false}else{target.copy(player.position).add(new THREE.Vector3(0,1.4,0));const off=new THREE.Vector3(-Math.sin(yaw)*6,3.3,-Math.cos(yaw)*6);camera.position.lerp(target.clone().add(off),1-Math.pow(.001,dt));camera.lookAt(target);gun.visible=true}}
function update(dt){let dx=0,dz=0;if(keys.w)dz-=1;if(keys.s)dz+=1;if(keys.a)dx-=1;if(keys.d)dx+=1;if(dx||dz){const len=Math.hypot(dx,dz);dx/=len;dz/=len;const sy=Math.sin(yaw),cy=Math.cos(yaw);player.position.x+=(dx*cy-dz*sy)*8*dt;player.position.z+=(dx*sy+dz*cy)*8*dt}player.position.x=THREE.MathUtils.clamp(player.position.x,-80,80);player.position.z=THREE.MathUtils.clamp(player.position.z,-80,80);for(const it of items){if(it.userData.held){it.position.copy(player.position).add(new THREE.Vector3(Math.sin(yaw)*1.4,1.1,Math.cos(yaw)*1.4));continue}it.position.addScaledVector(it.userData.v,dt);it.userData.v.multiplyScalar(Math.pow(.08,dt));it.position.y=Math.max(.5,it.position.y);if(Math.abs(it.position.x)>88)it.userData.v.x*=-.7;if(Math.abs(it.position.z)>88)it.userData.v.z*=-.7}for(const b of bots){b.o.position.addScaledVector(b.dir,dt*2);if(Math.random()<.006)b.dir.applyAxisAngle(new THREE.Vector3(0,1,0),(Math.random()-.5)*2);if(Math.abs(b.o.position.x)>75||Math.abs(b.o.position.z)>75)b.dir.negate()}setCamera(dt)}
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);if(running)update(dt);renderer.render(scene,camera)} loop();
function start(){running=true;document.body.classList.add('running');document.getElementById('menu').style.display='none';document.getElementById('hud').style.display='flex';document.getElementById('mode').textContent=first?'1 ЛИЦО':'3 ЛИЦО'}
function toggle(){first=!first;document.getElementById('mode').textContent=first?'1 ЛИЦО':'3 ЛИЦО';flash(first?'ПЕРВОЕ ЛИЦО':'ТРЕТЬЕ ЛИЦО')}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key==='1')first=true;if(e.key==='3')first=false;if(e.key.toLowerCase()==='v')toggle();if(e.key.toLowerCase()==='e')use();if(e.key.toLowerCase()==='q')throwIt();if(e.key.toLowerCase()==='f')shoot()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);document.getElementById('play').onclick=start;document.getElementById('cam').onclick=toggle;document.getElementById('fire').onclick=shoot;document.getElementById('use').onclick=use;document.getElementById('throw').onclick=throwIt;
let dragging=false,lx=0,ly=0;addEventListener('pointerdown',e=>{if(e.target.closest('#touch')||!running)return;dragging=true;lx=e.clientX;ly=e.clientY});addEventListener('pointerup',()=>dragging=false);addEventListener('pointermove',e=>{if(!dragging)return;const x=e.clientX-lx,y=e.clientY-ly;lx=e.clientX;ly=e.clientY;yaw-=x*.006;pitch=THREE.MathUtils.clamp(pitch-y*.006,-1.2,1.2)});
let joy=false,jx=0,jy=0;const stick=document.getElementById('stick'),knob=document.getElementById('knob');stick.addEventListener('pointerdown',e=>{joy=true;stick.setPointerCapture(e.pointerId)});stick.addEventListener('pointerup',()=>{joy=false;knob.style.left='34px';knob.style.top='34px';keys.w=keys.a=keys.s=keys.d=false});stick.addEventListener('pointermove',e=>{if(!joy)return;const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=e.clientX-cx,y=e.clientY-cy;const m=Math.min(45,Math.hypot(x,y));const a=Math.atan2(y,x);x=Math.cos(a)*m;y=Math.sin(a)*m;knob.style.left=(34+x)+'px';knob.style.top=(34+y)+'px';keys.d=x>12;keys.a=x<-12;keys.s=y>12;keys.w=y<-12});
